src/accounts/urls.py
from django.urls import path

from accounts import views

urlpatterns = [
    path('signup', views.Signup.as_view(), name='signup'),
]

src/catalogue/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path


urlpatterns = [

    path("select2/", include("django_select2.urls")),
    path(
        '', include(
            ('teaching.urls', 'teaching'),
            namespace='teaching')
    ),

    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/teaching/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework import routers
from . import views, api_views


router = routers.DefaultRouter()
router.register(r'course_material', api_views.CourseMaterialViewSet)
router.register(r'organization', api_views.OrganizationViewSet)


urlpatterns = [
    path('', views.LastCourseList.as_view(), name='index'),
    path('coursematerial', views.CourseMaterialList.as_view(), name='coursematerial-list'),
    path('coursematerial/pending', views.CourseMaterialPendingList.as_view(), name='coursematerial-pending-list'),
    path('coursematerial/<int:pk>', views.CourseMaterialDetail.as_view(), name='coursematerial-detail'),
    path('coursematerial/add', views.CourseMaterialCreateView.as_view(), name='coursematerial-create'),
    path('coursematerial/thanks', TemplateView.as_view(template_name="teaching/thanx.html"), name='coursematerial-thanx'),
    path('coursematerial/<int:pk>/edit', views.CourseMaterialUpdateView.as_view(), name='coursematerial-update'),
    path('coursematerial/<int:pk>/changestatus', views.CourseMaterialChangeStatusView.as_view(), name='coursematerial-change-status'),
    path('organization', views.OrganizationList.as_view(), name='organization-list'),
    path('organization/add', views.OrganizationCreateView.as_view(), name='organization-create'),
    path('organization/thanks', TemplateView.as_view(template_name="teaching/thanx.html"), name='organization-thanx'),
    path('organization/<int:pk>/edit', views.OrganizationUpdateView.as_view(), name='organization-update'),
]

urlpatterns += path('api/', include((router.urls, 'teaching'))),

src/teaching/models.py
from django.db import models
from django.utils.translation import gettext as _


class LabelDescriptionModelMixin(models.Model):
    """Label Description model mixin"""
    label = models.CharField(_('Label'), max_length=200, blank=True, null=True)
    description = models.TextField(_("Description"), blank=True, null=True)

    class Meta:
        abstract = True
        ordering = ['label']

    def __str__(self):
        return self.label


class PublicationStatus(models.TextChoices):
    """Publication status choices"""
    DRAFT = 'DRAFT', _('Draft')
    PENDING = 'PENDING', _('Pending')
    PUBLISHED = 'PUBLISHED', _('Published')
    REFUSED = 'REFUSED', _('Refused')


class Author(models.Model):
    """Model for Author"""
    name = models.CharField(_('Name'), max_length=100)

    class Meta:
        verbose_name = _('author')
        verbose_name_plural = _('authors')
        ordering = ['name']

    def __str__(self):
        return self.name


class Organization(models.Model):
    """Model for organization"""
    name = models.CharField(_('Name'), max_length=255)
    description = models.TextField(_('Description'), blank=True, null=True)
    website = models.URLField(_('Website'), max_length=200, blank=True, null=True)
    address = models.CharField(_('Address'), max_length=255, blank=True, null=True)
    city = models.CharField(_('City'), max_length=255, blank=True, null=True)
    contact_email = models.EmailField(_('Email'), blank=True, null=True)

    class Meta:
        verbose_name = _('Organization')
        verbose_name_plural = _('Organizations')
        ordering = ['name']

    def __str__(self):
        return self.name


class License(models.Model):
    """Model for License"""
    code = models.CharField(_('Code'), max_length=80)
    title = models.CharField(_('Title'), max_length=200, blank=True, null=True)
    description = models.TextField(_("Description"), blank=True, null=True)
    url = models.URLField('URL', max_length=200, blank=True, null=True)

    class Meta:
        verbose_name = _('license')
        verbose_name_plural = _('license')
        ordering = ["title"]

    def __str__(self):
        return self.title


class Level(LabelDescriptionModelMixin):
    """Model for Level"""

    class Meta:
        verbose_name = _('level')
        verbose_name_plural = _('levels')


class Tag(LabelDescriptionModelMixin):
    """Model for Level"""

    class Meta:
        verbose_name = _('tag')
        verbose_name_plural = _('tags')


class CourseMaterial(models.Model):
    """Model for CourseMaterial"""

    title = models.CharField(_('Title'), max_length=100)
    description = models.TextField(
        _('Description'),
        max_length=500, blank=True, null=True
    )
    tags = models.ManyToManyField(
        Tag,
        blank=True,
        related_name="course_materials"
    )
    status = models.CharField(
        _('Status'),
        max_length=10,
        choices=PublicationStatus.choices,
        default=PublicationStatus.PENDING
    )
    level = models.ForeignKey(
        Level,
        verbose_name=_('Level'),
        on_delete=models.SET_NULL,
        blank=True,
        null=True
    )
    author = models.ForeignKey(
        Author,
        verbose_name=_('Author'),
        related_name='courses',
        on_delete=models.SET_NULL,
        blank=True,
        null=True
    )
    contributors = models.ManyToManyField(
        Author,
        verbose_name=_('Contributor'),
        related_name='contributed_courses',
        blank=True
    )
    organization = models.ForeignKey(
        Organization,
        verbose_name=_('Training organization'),
        related_name='courses',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    resource_license = models.ForeignKey(
        License,
        verbose_name=_('Resource License'),
        related_name='courses',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    course_url = models.URLField(
        'URL',
        max_length=200, blank=True, null=True
    )

    class Meta:
        verbose_name = _('course material')
        verbose_name_plural = _('course materials')
        ordering = ['title']
        permissions = [
            ('can_publish_coursematerial', 'Can publish CourseMaterial'),
        ]

    def __str__(self):
        return self.title

    @property
    def is_published(self):
        return self.status == PublicationStatus.PUBLISHED

src/teaching/forms.py
# Forms here
from django import forms
from django_select2 import forms as s2forms
from django.utils.translation import gettext as _
from teaching.models import CourseMaterial, Author, Organization, Tag


class AuthorWidget(s2forms.ModelSelect2Widget):
    search_fields = [
        "name__icontains",
    ]


class OrganizationWidget(s2forms.ModelSelect2Widget):
    search_fields = [
        "name__icontains",
        "description__icontains",
    ]


class LicenseWidget(s2forms.ModelSelect2Widget):
    search_fields = [
        "code__icontains",
        "title__icontains",
    ]


class TagsWidget(s2forms.ModelSelect2TagWidget):
    queryset = Tag.objects.all()
    search_fields = [
        "label__icontains",
    ]

    def build_attrs(self, base_attrs, extra_attrs=None):
        base_attrs = {
            "data-token-separators": '[","]',
        }
        return super().build_attrs(base_attrs, extra_attrs=extra_attrs)

    def value_from_datadict(self, data, files, name):
        """Create objects for given non-pimary-key values. Return list of all primary keys."""
        values = super().value_from_datadict(data, files, name)
        if not values:
            return ''
        pk_values = [int(v) for v in values if v.isdigit()]
        pks = set()
        if pk_values:
            pks = self.queryset.filter(**{'pk__in': list(pk_values)}).values_list('pk', flat=True)
            pks = set(map(str, pks))
        cleaned_values = pk_values
        for val in set(values) - pks:
            cleaned_values.append(self.queryset.create(label=val).pk)
        return cleaned_values


class ContributorsWidget(s2forms.ModelSelect2TagWidget):
    queryset = Author.objects.all()
    search_fields = [
        "name__icontains",
    ]

    def value_from_datadict(self, data, files, name):
        """Create objects for given non-pimary-key values. Return list of all primary keys."""
        values = super().value_from_datadict(data, files, name)
        if not values:
            return ''
        pk_values = [int(v) for v in values if v.isdigit()]
        pks = set()
        if pk_values:
            pks = self.queryset.filter(**{'pk__in': list(pk_values)}).values_list('pk', flat=True)
            pks = set(map(str, pks))
        cleaned_values = pk_values
        for val in set(values) - pks:
            cleaned_values.append(self.queryset.create(name=val).pk)
        return cleaned_values


class CourseMaterialForm(forms.ModelForm):
    """CourseMaterial publish form"""

    new_author = forms.CharField(required=False,
                           label=_("Author name"),
                           help_text=_("Enter author name if not in the list"))

    new_orga = forms.CharField(required=False,
                         label=_("Organization name"),
                         help_text=_("Enter organization name if not in the list"))

    class Meta:
        model = CourseMaterial
        fields = ("title",
                  "description",
                  "level",
                  "tags",
                  "course_url",
                  "author",
                  "new_author",
                  "contributors",
                  "resource_license",
                  "organization",
                  "new_orga")
        widgets = {
            'author': AuthorWidget,
            'contributors': ContributorsWidget,
            'resource_license': LicenseWidget,
            'organization': OrganizationWidget,
            'tags': TagsWidget,
        }

    def clean_author(self):
        author_selected = self.cleaned_data['author']
        author_name = self.data.get('new_author', '')
        if author_name != "":
            new_author, created = Author.objects.get_or_create(name=author_name)
            return new_author
        return author_selected

    def clean_organization(self):
        orga_selected = self.cleaned_data['organization']
        orga_name = self.data.get('new_orga', '')
        if orga_name != "":
            new_orga, created = Organization.objects.get_or_create(name=orga_name)
            return new_orga
        return orga_selected


class CourseMaterialPublishForm(forms.ModelForm):
    """CourseMaterial publish form"""

    class Meta:
        model = CourseMaterial
        fields = ("status",)


class CourseMaterialSearchForm(forms.Form):
    """CourseMaterial search form"""

    q_term = forms.CharField(
        label=_("Search in title and description"),
        required=False
    )
    q_tags = forms.MultipleChoiceField(
        label=_("Search in tags"),
        widget=s2forms.ModelSelect2MultipleWidget(
            model=Tag,
            search_fields=['label__icontains'],
        ),
        required=False,
    )
    q_published = forms.BooleanField(
        label=_("Published"),
        required=False,
    )

src/teaching/views.py
from django.urls import reverse_lazy
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.sites.models import Site
from django.db.models import Q, QuerySet
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.utils.translation import gettext as _

from teaching.models import CourseMaterial, Organization, Author, PublicationStatus, Tag
from teaching.forms import CourseMaterialForm, CourseMaterialPublishForm, CourseMaterialSearchForm


class LastCourseList(ListView):
    """Homepage view"""
    model = CourseMaterial
    template_name = 'index.html'
    queryset = CourseMaterial.objects.filter(status=PublicationStatus.PUBLISHED).order_by('?')[:3]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        site_used = Site.objects.get(id=settings.SITE_ID)
        if hasattr(settings, 'SITE_TITLE') and settings.SITE_TITLE:
            context['homepage_title'] = settings.SITE_TITLE
        elif site_used:
            context['homepage_title'] = site_used.name
        return context


class CourseMaterialList(ListView):
    """CourseMaterial list view"""
    model = CourseMaterial

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        initial_data = {}
        if 'q_term' in self.request.GET and self.request.GET.get('q_term') != '':
            initial_data['q_term'] = self.request.GET.get('q_term')
        if 'q_tags' in self.request.GET and self.request.GET.get('q_tags') != '':
            initial_data['q_tags'] = self.request.GET.get('q_tags')
        if len(self.request.GET) == 0 or self.request.GET.get('q_published') == 'on':
            initial_data['q_published'] = True
        context_data['search_form'] = CourseMaterialSearchForm(initial=initial_data)
        return context_data

    def get_queryset(self):
        q_term = self.request.GET.get('q_term', '')
        queryset = CourseMaterial.objects.all()
        if self.request.GET.get('q_published') or len(self.request.GET) == 0:
            queryset = queryset.filter(status=PublicationStatus.PUBLISHED)
        if q_term:
            queryset = queryset.filter(
                Q(title__icontains=q_term) | Q(description__icontains=q_term)
            )
        q_tags = self.request.GET.get('q_tags', '')
        if q_tags:
            queryset = queryset.filter(tags__in=q_tags)
        return queryset


class CourseMaterialPendingList(ListView):
    model = CourseMaterial
    template_name = "teaching/coursematerial_pending_list.html"
    queryset = CourseMaterial.objects.exclude(status=PublicationStatus.PUBLISHED)

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['form'] = CourseMaterialPublishForm()
        return context


class CourseMaterialDetail(DetailView):
    """CourseMaterial detail view"""
    model = CourseMaterial


class CourseMaterialCreateView(CreateView):
    """CourseMaterial create view"""
    model = CourseMaterial
    form_class = CourseMaterialForm
    template_name = 'teaching/coursematerial_form.html'
    success_url = reverse_lazy('teaching:coursematerial-thanx')


class CourseMaterialUpdateView(PermissionRequiredMixin, UpdateView):
    """CourseMaterial update view"""
    model = CourseMaterial
    permission_required = "teaching.change_coursematerial"
    form_class = CourseMaterialForm
    template_name = 'teaching/coursematerial_form.html'
    success_url = reverse_lazy('teaching:coursematerial-list')


class CourseMaterialChangeStatusView(PermissionRequiredMixin, UpdateView):
    """CourseMaterial change status view"""
    model = CourseMaterial
    permission_required = "teaching.change_coursematerial"
    form_class = CourseMaterialPublishForm
    success_url = reverse_lazy('teaching:coursematerial-pending-list')


class OrganizationList(ListView):
    """Organization list view"""
    model = Organization


class OrganizationCreateView(LoginRequiredMixin, CreateView):
    """Organization create view"""
    model = Organization
    fields = ("name", "description", "website", "contact_email", "address", "city")
    template_name = 'teaching/organization_form.html'
    success_url = reverse_lazy('teaching:organization-list')


class OrganizationUpdateView(PermissionRequiredMixin, UpdateView):
    """Organization create view"""
    model = Organization
    permission_required = "teaching.change_organization"
    fields = ("name", "description", "website", "contact_email", "address", "city")
    template_name = 'teaching/organization_form.html'
    success_url = reverse_lazy('teaching:organization-list')

src/teaching/templates/teaching/author_form.html
boo

src/teaching/templates/teaching/coursematerial_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{{ coursematerial }}{% endblock %}

{% block main-class %}container{% endblock %}

{% block content %}

<div class="row justify-content-md-center">
  <div class="col-md-10 col-lg-6">
    <a href="{% url 'teaching:coursematerial-list' %}">← {% trans "Back to the list" %}</a>
    <h1>{{ coursematerial }}</h1>
    <p class="small">{% trans "by" %} {{ coursematerial.author.name }}

    {% if coursematerial.contributors.all %}<br>
    {% for contributor in coursematerial.contributors.all %}
      {{ contributor }}{% if not forloop.last %},{% endif %}
    {% endfor %}
    {% endif %}

    {% if coursematerial.tags.all %}<br>
    {% for tag in coursematerial.tags.all %}
      {{ tag }}{% if not forloop.last %},{% endif %}
    {% endfor %}
    {% endif %}
    </p>

    {% if coursematerial.resource_license %}
    <p><strong>{% trans "License:" %}</strong> {{ coursematerial.resource_license }}</p>
    {% endif %}
    {% if coursematerial.level %}
    <p><strong>{% trans "Level:" %}</strong> {{ coursematerial.level }}</p>
    {% endif %}

    <p>{{ coursematerial.description }}</p>

    {% if coursematerial.url %}
    <p>
      🔗 <a href="{{ coursematerial.url }}" target="_blank">{% trans "Link" %}</a>
    </p>
    {% endif %}

    {% if perms.teaching.change_coursematerial %}
    <p class="text-right">
      <a class="btn btn-primary" href="{% url 'teaching:coursematerial-update' coursematerial.pk %}">{% trans "Edit" %}</a>
    </p>
    {% endif %}

  </div>
</div>

{% endblock %}

src/teaching/templates/teaching/coursematerial_form.html
{% extends "base.html" %}
{% load static i18n bootstrap4 %}

{% block title %}{% trans "Add / Edit course material" %}{% endblock %}

{% block extra_head %}
{{ form.media.css }}
<style>
    input, select {width: 100%}
</style>
{% endblock %}

{% block extra_js%}
{{ form.media.js }}
{% endblock %}

{% block main-class %}container{% endblock %}

{% block content %}
<div class="row justify-content-md-center">
  <div class="col-md-10 col-lg-6">

    <h1>{% trans "Add course material" %}</h1>

    <form method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
      <div class="text-right">
        <a href="{% url 'teaching:coursematerial-list'  %}">
          {% trans "Cancel" %}
        </a>
        {% bootstrap_button "Save" button_type="submit" button_class="btn-success" %}
      </div>
      {% endbuttons %}
    </form>

  </div>

</div>

{% endblock %}

src/teaching/templates/teaching/coursematerial_list.html
{% extends "base.html" %}
{% load static i18n bootstrap4 %}

{% block title %}{% trans "Course material list" %}{% endblock %}

{% block extra_head %}
{{ search_form.media.css }}
<style>
    input, select {width: 100%}
    #id_q_term,
    .select2-container {width: 340px !important ;}
    .form-inline .form-check-input
    {
        flex-shrink: 1;
    }
</style>
{% endblock %}

{% block extra_js%}
{{ search_form.media.js }}
{% endblock %}

{% block main-class %}container{% endblock %}

{% block content %}

<h1>{% trans "Course material list" %}</h1>
<p class="text-right">
  <a class="btn btn-primary"
  href="{% url 'teaching:coursematerial-create' %}" %}>
    {% trans "Add a resource" %}
  </a>
</p>

<div class="search-form mb-4">

<form action="{% url 'teaching:coursematerial-list' %}" method="get">
    <div class="form-inline">
        {% bootstrap_field search_form.q_term layout='inline' form_group_class='form-group mr-sm-2' %}
        {% bootstrap_field search_form.q_tags layout='inline' form_group_class='form-group mr-sm-2' %}
        {% bootstrap_field search_form.q_published layout='inline' form_group_class='form-group mr-sm-2' %}
        {% buttons form_group_class='form-group ml-sm-4' %}
        {# {% bootstrap_button "Reset" button_type="reset" button_class="btn-light mr-2" %} #}
        {% bootstrap_button "Search" button_type="submit" button_class="btn-success" %}
        {% endbuttons %}
    </div>
</form>
</div>

{% if object_list %}

<div class="row">

  {% for course in object_list %}
  <div class="col-sm-6 col-md-4">
    <div class="card mb-3 {{ course.status|lower }}">
      {% include "teaching/_partials/course_card.html" %}
    </div>
  </div>
  {% endfor %}

</div>

{% else %}

<p>{% trans "No resource!" %}</p>

{% endif %}

<p class="text-right">
  <a href="{% url 'teaching:coursematerial-pending-list' %}">&RightArrow; {% trans "Pending course material list" %}</a>
</p>

{% endblock %}

src/teaching/templates/teaching/coursematerial_pending_list.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Pending course material list" %}{% endblock %}

{% block content %}

<h1>{% trans "Pending course material list" %}</h1>

{% if object_list %}

<table class="table">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th class="d-none d-sm-table-cell">Meta</th>
    {% if perms.teaching.change_coursematerial %}
    <th>Actions</th>
    {% endif %}
  </tr>
  {% for course in object_list %}
  <tr>
    <td>
      <h2 class="h3"><a href="{% url 'teaching:coursematerial-detail' course.id %}">{{ course }}</a></h2>
      <small>
      by {{ course.author }}<br>
      {% if course.resource_license %}
      {{ course.resource_license }}
      {% else %}
      {% trans "Non libre" %}
      {% endif %}
      {% if course.level %}<br>
      {{ course.level }}
      {% endif %}
      {% if course.tags.all %}<br>
      {% for tag in course.tags.all %}
        {{ tag }}{% if not forloop.last %},{% endif %}
      {% endfor %}
      {% endif %}
      </small>
    </td>
    <td>
      {{ course.description }}<br>
      <a href="{{ course.course_url }}" target="_blank">
        <span>{% trans "Direct link" %}</span>
      </a>
    </td>
    <td class="d-none d-sm-table-cell">
      {{ course.level }}<br>
      {{ course.license }}<br>
    </td>
    {% if perms.teaching.change_coursematerial %}
    <td>
        <p>
          <a class="btn btn-primary btn-sm" href="{% url 'teaching:coursematerial-update' course.id %}">Edit</a>
        </p>
        {{ course.status }}
        <form action="{% url 'teaching:coursematerial-change-status' course.id %}" method="post">
          {% csrf_token %}
          {{ form.status }}
          <input class="btn btn-success btn-sm" type="submit" value="Ok" />
        </form>
      </td>
      {% endif %}
  </tr>
  {% endfor %}
</table>

{% else %}

<p>{% trans "No pending courses." %}</p>

{% endif %}

{% endblock %}

src/teaching/templates/teaching/organization_form.html
{% extends "base.html" %}
{% load i18n %}
{% load bootstrap4 %}

{% block title %}{% trans "Add / Edit training organization" %}{% endblock %}

{% block content %}
<div class="row justify-content-md-center">
  <div class="col-md-6 col-lg-5">

    <h1>{% trans "Add an organization" %}</h1>

    <form method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
      <div class="text-right">
        <a href="{% url 'teaching:organization-list'  %}">
          {% trans "Cancel" %}
        </a>

        {% bootstrap_button "Save" button_type="submit" button_class="btn-success" %}
      </div>
      {% endbuttons %}
    </form>

  </div>

</div>

{% endblock %}

src/teaching/templates/teaching/organization_list.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Training organization list" %}{% endblock %}

{% block main-class %}container{% endblock %}

{% block content %}

<h1>{% trans "Organization list" %}</h1>

{% if perms.teaching.add_trainingorganization %}
<p class="text-right">
  <a class="btn btn-primary"
  href="{% url 'teaching:organization-create' %}">
    {% trans "Add an organization" %}
  </a>
</p>
{% endif %}

{% if object_list %}

<div class="row">

  {% for orga in object_list %}
  <div class="col-sm-12 col-md-6">
    <div class="card mb-3">

      <div class="card-body">
        <h2 class="card-title">{{ orga }}</h2>
        <p class="card-text">{{ orga.description }}</p>
      </div>
      <div class="card-footer small d-flex">
        <div class="meta flex-grow-1">
          {% if orga.city %}
          <span class="city">{{ orga.city }}</span><br>
          {% endif %}
          {% if orga.website %}
          <span class="link"><a class="card-link" target="_blank" href="{{ orga.website }}">{% trans "Website" %}</a></span>
          {% endif %}
        </div>
        <div>
          {% if perms.teaching.change_trainingorganization %}
          <a href="{% url 'teaching:organization-update' orga.pk %}" class="btn btn-secondary btn-sm">{% trans "Edit" %}</a>
          {% endif %}
        </div>
      </div>

    </div>
  </div>
  {% endfor %}

</div>

{% else %}

<p>{% trans "No organization!" %}</p>

{% endif %}

{% endblock %}

src/teaching/templates/teaching/thanx.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Thank you!" %}{% endblock %}

{% block content %}
<h1>{% trans "Thank you!" %}</h1>
<p>
{% trans "Thank you for your submission, it will be soon reviewed."%}
</p>

{% endblock %}