src/accounts/urls.py
from django.urls import path

from accounts import views

urlpatterns = [
    path('signup', views.Signup.as_view(), name='signup'),
]

src/catalogue/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path


urlpatterns = [

    path("select2/", include("django_select2.urls")),
    path(
        '', include(
            ('teaching.urls', 'teaching'),
            namespace='teaching')
    ),

    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/teaching/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework import routers
from . import views, api_views


router = routers.DefaultRouter()
router.register(r'course_material', api_views.CourseMaterialViewSet)
router.register(r'organization', api_views.OrganizationViewSet)


urlpatterns = [
    path('', views.LastCourseList.as_view(), name='index'),
    path('coursematerial', views.CourseMaterialList.as_view(), name='coursematerial-list'),
    path('coursematerial/pending', views.CourseMaterialPendingList.as_view(), name='coursematerial-pending-list'),
    path('coursematerial/<int:pk>', views.CourseMaterialDetail.as_view(), name='coursematerial-detail'),
    path('coursematerial/add', views.CourseMaterialCreateView.as_view(), name='coursematerial-create'),
    path('coursematerial/thanks', TemplateView.as_view(template_name="teaching/thanx.html"), name='coursematerial-thanx'),
    path('coursematerial/<int:pk>/edit', views.CourseMaterialUpdateView.as_view(), name='coursematerial-update'),
    path('coursematerial/<int:pk>/changestatus', views.CourseMaterialChangeStatusView.as_view(), name='coursematerial-change-status'),
    path('organization', views.OrganizationList.as_view(), name='organization-list'),
    path('organization/add', views.OrganizationCreateView.as_view(), name='organization-create'),
    path('organization/thanks', TemplateView.as_view(template_name="teaching/thanx.html"), name='organization-thanx'),
    path('organization/<int:pk>/edit', views.OrganizationUpdateView.as_view(), name='organization-update'),
]

urlpatterns += path('api/', include((router.urls, 'teaching'))),

src/catalogue/templates/index.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Homepage" %}{% endblock %}

{% block main-class %}container{% endblock %}

{% block content %}
<h1>
    Ressources pédagogiques libres pour le numérique
</h1>
<h2>
    Mettre en commun des ressources pédagogiques pour l'éducation populaire au numérique
</h2>
<p>Projet d'application web pour mettre en commun des ressources pédagogique pour une
    l'éducation populaire au numériques. Il fait référence au projet
    <a href="https://potcommun.adn56.net/" target="_blank">Pot commun</a>
</p>
<h2>{% trans "Three random resources" %}</h2>
<div class="row">

    {% for course in object_list %}
    <div class="col-sm-6 col-lg-4">
        <div class="card mb-3">
            {% include "teaching/_partials/course_card.html" %}
        </div>
    </div>
    {% endfor %}

</div>

<p class="text-right"><a href="{% url 'teaching:coursematerial-list' %}">&RightArrow; {% trans "See all resources" %}</a></p>

{% endblock %}